export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const TODOS_LOADING = "TODOS_LOADING";
export const TODOS_SUCCESS = "TODOS_SUCCESS";
export const TODOS_ERROR = "TODOS_ERROR";

export const PROJECTS_ERROR = "PROJECTS_ERROR";
export const LOADING_PROJECTS = "LOADING_PROJECTS";
export const ADD_UPDATED_PROJECT = "ADD_UPDATED_PROJECT";
export const ADD_PROJECTS = "ADD_PROJECTS";
export const ADD_TO_PROJECTS = "ADD_TO_PROJECTS";

export const FRIENDS_ERROR = "FRIENDS_ERROR";
export const LOADING_FRIENDS = "LOADING_FRIENDS";
export const ADD_UPDATED_FRIEND = "ADD_UPDATED_FRIEND";
export const ADD_FRIEND = "ADD_FRIEND";

export const GISTS_LOADING = "GISTS_LOADING";
export const GISTS_SUCCESS = "GISTS_SUCCESS";
export const GISTS_ERROR = "GISTS_ERROR";